In [1]:
import syft
import syft.nn as nn
from syft.controller import tensors, models
import imp
imp.reload(syft.controller)
imp.reload(syft.nn)
imp.reload(syft)

import numpy as np
from syft import FloatTensor, IntTensor

D:\SoftwareInstalls\Anaconda\envs\openmined\lib\site-packages\ipython-6.2.1-py3.6.egg\IPython\html.py:14: ShimWarning: The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)


In [2]:
# create tensors
data = np.array([-1,-2,3,4,5,-6]).astype('float')
a = FloatTensor(data)
b = FloatTensor(np.array([[-100,-200,300],[400,500,-600]]).astype('float'))
c = FloatTensor(np.array([-30,-32,33,34,35,-36]).astype('float')) 
d = FloatTensor(np.random.rand(2,6))

In [3]:
x = FloatTensor(list(range(1,25))).view(3,4,2).autograd(True)
y = FloatTensor(list(range(26,50))).view(3,4,2).autograd(True)


In [4]:

xi = IntTensor([1,3,34])

In [5]:
xi.exp()

[         2         20 2147483647]
[syft.IntTensor:2 size:3]

In [ ]:
z = syft.concatenate([x,y],axis=0)

In [ ]:
z_grad = (z * 1).autograd(False)

In [ ]:
z.backward(z_grad)

In [ ]:
y.grad()

In [ ]:
np.concatenate([x.to_numpy(),y.to_numpy()],axis=2)

In [ ]:
y

In [ ]:
xi

In [ ]:
y.save("y.tensor")

In [ ]:
syft.load('y.tensor')

In [ ]:
x.save("x.tensor")

In [ ]:
x

In [ ]:
y

In [ ]:
out = a.view_(2,3)

In [ ]:
out

In [ ]:
# using view_as should return new tensor with shape of given tensor
a.view_as(b)
# should be
#[[-1. -2.  3.]
# [ 4.  5. -6.]]

In [ ]:
b.view_as(c)
# should be
# [-100. -200.  300.  400.  500. -600.]

In [ ]:
c.view_as(b)
# should be
#[[-30. -32.  33.]
# [ 34.  35. -36.]]

In [ ]:
d = b.view_as(c)
# d should be [-100. -200.  300.  400.  500. -600.]
d

### CPU vs GPU

In [ ]:
gpu = True

### Absolute Value

In [ ]:
a = FloatTensor(data)

if(gpu):
    a.gpu()

In [ ]:
b = a.abs()
b

In [ ]:
a = FloatTensor(data)
if(gpu):
    a.gpu()

In [ ]:
a

In [ ]:
a.abs_()

In [ ]:
a.id

### Addition

In [ ]:
a = FloatTensor(data)
if(gpu):
    a.gpu()

In [ ]:
a

In [ ]:
a = a + a
a

In [ ]:
a += a
a

In [ ]:
a = a + 3
a

In [ ]:
a += 3
a

### Subtraction

In [ ]:
a = FloatTensor(data)
b = FloatTensor(data * 2)
if(gpu):
    a.gpu()
    b.gpu()

In [ ]:
a

In [ ]:
b

In [ ]:
a - b

In [ ]:
b - a

In [ ]:
a - 1

In [ ]:
b - 2

In [ ]:
a -= 1
a

In [ ]:
b -= 1
b

In [ ]:
a -= b
a

## Multiplication

In [ ]:
a = a * a
a

In [ ]:
a *= a
a

In [ ]:
a = a * 3
a

In [ ]:
a *= 3
a

### Divison

In [ ]:
a

In [ ]:
b

In [ ]:
a = a/a
a

In [ ]:
b / a

In [ ]:
a / b

In [ ]:
a / 1

In [ ]:
b / 1

In [ ]:
a /= b
a

In [ ]:
b /= a
b

In [ ]:
a /= a
a

In [ ]:
b /= 1
b

In [ ]:
b /= 2
b

In [ ]:
a *= 2

In [ ]:
a

### Max

In [ ]:
tensor_1 = IntTensor(np.array([[-100,-200,300],[400,500,-600]]).astype('int'))
tensor_2 = IntTensor(np.array([[100,-300,100],[200,800,-200]]).astype('int'))


In [ ]:
tensor_1.max_(tensor_2)

In [ ]:
syft.max_()